# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'Asthm App' do
  	# Comment the next line if you don't want to use dynamic frameworks
  	use_frameworks!

  	# Pods for Asthm App
  
  	pod 'common', :path => '../common'

  	pod 'TinyConstraints'
  	pod 'SDWebImage', '~> 5.0'
  	pod 'PKHUD', '~> 5.0'
	  pod 'MaterialComponents/Buttons'
	  pod 'Toast-Swift', '~> 5.0.1'
	  pod 'lottie-ios'
    pod 'PKHUD', '~> 5.0'
    pod 'Firebase/Auth'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'GoogleSignIn'
    pod 'FacebookCore'
    pod 'FacebookLogin'
	  pod 'Charts'
    pod 'GoogleMaps', '4.0.0'
    pod 'Firebase/Messaging'

  	target 'Asthm AppTests' do
    	inherit! :search_paths
    		# Pods for testing
  	end

  	target 'Asthm AppUITests' do
    		# Pods for testing
  	end

end
